function g = gmfile(in1)
%GMFILE
%    G = GMFILE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Apr-2024 18:46:55

x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
phi = in1(4,:);
theta = in1(5,:);
psi = in1(6,:);
t2 = cos(phi);
t3 = cos(theta);
t4 = sin(phi);
t5 = sin(theta);
g = [t5.*-2.094180000000051e+2;t3.*t4.*2.094180000000051e+2;t2.*t3.*2.094180000000051e+2;t2.*t3.*-1.423280935999937e+2+t3.*t4.*7.157069849600084e+3;t5.*7.157069849600084e+3-t2.*t3.*1.51939860960003e+3;t5.*-1.423280935999937e+2+t3.*t4.*1.51939860960003e+3];
end
